// Create Job API - creates a new generation job with mock support

import { generateUUID } from '../../utils/storage';
import { getMockDatabase } from '../storage/mockDatabase';
import { getMockStoryQueue, clearAllMockQueues } from '../queue/mockQueue';

import { VideoConfigContext } from '../types';
import { StoryTimeline } from '../../types';

export interface CreateJobRequest {
  userId: string;
  templateId: string;
  profileId?: string;
  prompt: string;
  videoConfig?: Partial<VideoConfigContext>;
  textModel?: string; // Optional model field for script generation
}

export interface CreateJobResponse {
  success: boolean;
  jobId: string;
  storyId: string;
  isMock?: boolean;
  error?: string;
}

export class CreateJobAPI {
  private env: any;
  private useMock: boolean;
  private requestUrl?: string;

  constructor(env: any, requestUrl?: string) {
    this.env = env;
    this.requestUrl = requestUrl;
    this.useMock = env.GEN_PROVIDER === 'mock' || env.GEN_PROVIDER === 'mock';
    console.log('[CreateJob] GEN_PROVIDER:', env.GEN_PROVIDER, 'useMock:', this.useMock);
  }

  private getBaseUrl(): string {
    if (this.requestUrl) {
      return new URL(this.requestUrl).origin;
    }
    return 'https://create-story-worker.artflicks.workers.dev';
  }

  async execute(request: CreateJobRequest): Promise<CreateJobResponse> {
    try {
      const { getTemplate } = await import('../templates/index');
      const { profileRegistry } = await import('../profiles/index');

      const template = getTemplate(request.templateId);
      if (!template) {
        return { success: false, jobId: '', storyId: '', error: `Unknown template: ${request.templateId}` };
      }
      const profileId = request.profileId || template.profileId;
      const profile = profileRegistry.get(profileId);
      if (!profile) {
        return { success: false, jobId: '', storyId: '', error: `Unknown profile: ${profileId}` };
      }

      const jobId = generateUUID();
      const storyId = generateUUID();

      const videoConfig = {
        ...template.defaultConfig.videoConfig,
        ...request.videoConfig,
        templateId: request.templateId,
        sceneReviewRequired: request.videoConfig?.enableSceneReview ?? false,
      };

      // DAG-driven: Create story with empty scenes - DAG will generate script first
      const storyData: StoryTimeline = { 
        id: storyId,
        title: undefined,
        totalDuration: 0,
        scenes: [] 
      };

      console.log('[CreateJob] DAG-driven: Script will be generated by DAGExecutor');

      const { createClient } = await import('@supabase/supabase-js');
      const supabase = createClient(this.env.SUPABASE_URL, this.env.SUPABASE_SERVICE_ROLE_KEY);

      const { error: insertError } = await supabase
        .from('stories')
        .insert({
          id: storyId,
          user_id: request.userId,
          story: storyData,
          video_type: (videoConfig as any).videoType || 'shorts',
          video_config: videoConfig,
          status: 'pending',
          created_at: new Date().toISOString(),
        });

      if (insertError) {
        console.error('[CreateJob] Failed to create story:', insertError);
        return { success: false, jobId, storyId, error: insertError.message };
      }

      const { error: jobError } = await supabase
        .from('story_jobs')
        .insert({
          job_id: jobId,
          story_id: storyId,
          user_id: request.userId,
          status: 'pending',
          progress: 0,
          total_scenes: storyData.scenes?.length || 0,
          images_generated: 0,
          audio_generated: 0,
          team_id: request.videoConfig?.teamId || null,
        });

      if (jobError) {
        console.error('[CreateJob] Failed to create job:', jobError);
        return { success: false, jobId, storyId, error: jobError.message };
      }

       // Initialize DO (generation-engine architecture) - for state storage only
       console.log('[CreateJob] Initializing Durable Object for story state storage', storyId);
       
       const coordinatorId = this.env.STORY_COORDINATOR.idFromName(storyId);
       const coordinator = this.env.STORY_COORDINATOR.get(coordinatorId);
 
       // Build jobMetadata to pass to DO
       const jobMetadata = {
         jobId,
         userId: request.userId,
         seriesId: videoConfig.seriesId || '',
         storyId,
         storyData,
         baseUrl: this.getBaseUrl(),
         userTier: videoConfig.userTier || 'tier1',
         priority: 1,
         teamId: videoConfig.teamId,
       };
 
       await coordinator.fetch(new Request('http://do/init', {
         method: 'POST',
         body: JSON.stringify({
           storyId,
           jobId,
           userId: request.userId,
           scenes: storyData.scenes,
           totalScenes: storyData.scenes.length,
           videoConfig,
           skipAudioCheck: !videoConfig.enableVoiceOver,
           sceneReviewRequired: videoConfig.sceneReviewRequired || false,
           jobMetadata,
         }),
       }));
 
       console.log('[CreateJob] Durable Object initialized for state storage');
       
       // Use DAGExecutor to drive the job flow (orchestration)
       console.log('[CreateJob] Initializing DAGExecutor for job orchestration');
       const { createDAGExecutor } = await import('../workflow/dagExecutor');
       const dagExecutor = createDAGExecutor({
         env: this.env,
         message: {
            jobId,
            storyId,
            userId: request.userId,
            templateId: request.templateId,
            videoConfig,
            seriesId: videoConfig.seriesId || '',
            title: storyData.title,
            baseUrl: this.getBaseUrl(),
            teamId: videoConfig.teamId,
            userTier: videoConfig.userTier || 'tier1',
            priority: 1,
          }
        });
       
       const executionResult = await dagExecutor.run();
       if (!executionResult.success) {
         console.error('[CreateJob] DAGExecutor failed to run:', executionResult.error);
         // Mark job as failed in DB
         await this.updateProgress(jobId, 0, 'failed');
         return { success: false, jobId: '', storyId: '', error: executionResult.error };
       }
       
       console.log('[CreateJob] DAGExecutor initialized and scheduled initial nodes');

      return { success: true, jobId, storyId };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.error('[CreateJob] Error:', message);
      return { success: false, jobId: '', storyId: '', error: message };
    }
  }

  async completeJob(jobId: string, storyId: string, userId: string, story: any, teamId?: string, timeline?: unknown): Promise<{ success: boolean; storyUrl?: string; error?: string }> {
    try {
      const { createStorySyncService } = await import('../services/storySync');
      const { createEmailNotificationService } = await import('../services/emailNotification');

      const syncService = createStorySyncService(this.env);
      const emailService = createEmailNotificationService(this.env);

      const syncResult = await syncService.syncStoryComplete(
        { jobId, storyId, userId, teamId, timeline },
        story
      );

      if (!syncResult.success) {
        return { success: false, error: syncResult.error };
      }

      let thumbnailUrl: string | undefined;
      if (story.scenes?.length > 0) {
        const firstWithImage = story.scenes.find((s: any) => s.generatedImageUrl);
        if (firstWithImage) {
          thumbnailUrl = firstWithImage.generatedImageUrl;
        }
      }

      await emailService.sendCompletionEmail({
        userId,
        storyId,
        storyTitle: story.title || 'Your Story',
        storyUrl: syncResult.storyUrl,
        thumbnailUrl,
      });

      return { success: true, storyUrl: syncResult.storyUrl };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.error('[CreateJob] CompleteJob Error:', message);
      return { success: false, error: message };
    }
  }

  async updateProgress(
    jobId: string,
    progress: number,
    status: string,
    imagesGenerated?: number,
    videosGenerated?: number,
    audioGenerated?: number
  ): Promise<void> {
    const { createStorySyncService } = await import('../services/storySync');
    const syncService = createStorySyncService(this.env);
    await syncService.updateJobProgress(jobId, progress, status, imagesGenerated, videosGenerated, audioGenerated);
  }
}

export function createCreateJobAPI(env: any, requestUrl?: string): CreateJobAPI {
  return new CreateJobAPI(env, requestUrl);
}
